import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';

export default function AlgebraicStructures_3_2() {
  
  // Custom Hierarchy Component
  const StructureNode = ({ name, description, properties }) => (
    <View style={styles.nodeContainer}>
      <View style={styles.nodeBox}>
        <Text style={styles.nodeName}>{name}</Text>
        <Text style={styles.nodeDesc}>{description}</Text>
      </View>
      <View style={styles.propertyPills}>
        {properties.map((p, i) => (
          <View key={i} style={styles.pill}><Text style={styles.pillText}>{p}</Text></View>
        ))}
      </View>
    </View>
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={{paddingBottom: 100}} showsVerticalScrollIndicator={false}>
      
      <Text style={styles.paragraph}>
        In this chapter, we explore various <Text style={styles.bold}>Algebraic Structures</Text>—sets equipped with binary operations that satisfy specific axioms or postulates.
      </Text>

      {/* SECTION 1: HIERARCHY OF STRUCTURES */}
      <Text style={styles.sectionHeader}>Hierarchy of Algebraic Structures</Text>
      
      <StructureNode 
        name="Semigroup" 
        description="A set S with binary operation 'o'."
        properties={["Closure", "Associativity"]}
      />
      <View style={styles.exampleBox}>
        <Text style={styles.exampleText}>Example: Positive integers {`{1, 2, 3...}`} under addition (+).</Text>
      </View>

      <StructureNode 
        name="Monoid" 
        description="A semigroup with an identity element (e or E)."
        properties={["Closure", "Associative", "Identity Element"]}
      />
      <View style={styles.exampleBox}>
        <Text style={styles.exampleText}>Example: Positive integers under multiplication where identity is 1.</Text>
      </View>

      <StructureNode 
        name="Group" 
        description="A monoid with an inverse element (I)."
        properties={["Closure", "Associative", "Identity", "Inverse"]}
      />
      <View style={styles.exampleBox}>
        <Text style={styles.exampleText}>Example: N × N non-singular matrices under multiplication.</Text>
      </View>

      <StructureNode 
        name="Abelian Group" 
        description="A group that always holds the Commutative Law."
        properties={["Closure", "Associative", "Identity", "Inverse", "Commutative"]}
      />
      <View style={styles.exampleBox}>
        <Text style={styles.exampleText}>Example: Integers Z under addition (+).</Text>
      </View>

      {/* SECTION 2: SPECIAL GROUPS */}
      <Text style={styles.sectionHeader}>Cyclic Groups and Subgroups</Text>
      <View style={styles.infoBox}>
        <Text style={styles.paragraph}>
          <Text style={styles.bold}>Cyclic Group:</Text> A group generated by a single element (generator g). Every element can be written as a power of g.
          {"\n\n"}
          <Text style={styles.bold}>Subgroup (H):</Text> A subset of group G (H ⊆ G) that satisfies closure, associativity, identity, and inverse.
        </Text>
      </View>

      {/* SECTION 3: POSET & HASSE DIAGRAMS */}
      <Text style={styles.sectionHeader}>Partially Ordered Set (POSET)</Text>
      <Text style={styles.paragraph}>
        A set with a binary relation that is <Text style={styles.bold}>reflexive, antisymmetric, and transitive</Text>.
      </Text>
      <View style={styles.exampleBox}>
        <Text style={styles.exampleText}>• Real numbers under operation (≤).</Text>
        <Text style={styles.exampleText}>• Vertex set of a directed acyclic graph under reachability.</Text>
      </View>

      <Text style={styles.subHeader}>Hasse Diagram Visualization</Text>
      <View style={styles.diagramContainer}>
        {/* Visual representation of image_7abd3c */}
        <MaterialCommunityIcons name="graph" size={80} color="#16941c" />
        <Text style={styles.caption}>Hasse Diagram: If x {"<"} y, point x is lower than y.</Text>
      </View>

      {/* SECTION 4: LATTICES */}
      <Text style={styles.sectionHeader}>Lattices and Their Properties</Text>
      <Text style={styles.paragraph}>
        A lattice is a POSET where every pair {`{a, b}`} has a <Text style={styles.bold}>Least Upper Bound (Join: ∨)</Text> and a <Text style={styles.bold}>Greatest Lower Bound (Meet: ∧)</Text>.
      </Text>

      <View style={styles.propertyCard}>
        <Text style={styles.propertyTitle}>Standard Lattice Types</Text>
        <Text style={styles.propertyText}>• <Text style={styles.bold}>Bounded:</Text> Has a greatest element 1 and least element 0.</Text>
        <Text style={styles.propertyText}>• <Text style={styles.bold}>Complemented:</Text> Bounded lattice where every element has a complement.</Text>
        <Text style={styles.propertyText}>• <Text style={styles.bold}>Distributive:</Text> a ∨ (b ∧ c) = (a ∨ b) ∧ (a ∨ c).</Text>
        <Text style={styles.propertyText}>• <Text style={styles.bold}>Modular:</Text> a ∧ (b ∨ (a ∧ d)) = (a ∧ b) ∨ (a ∧ d).</Text>
      </View>

      <View style={styles.lawCard}>
        <Text style={styles.propertyTitle}>Basic Lattice Laws</Text>
        <Text style={styles.lawRow}><Text style={styles.bold}>Idempotent:</Text> a ∨ a = a, a ∧ a = a</Text>
        <Text style={styles.lawRow}><Text style={styles.bold}>Absorption:</Text> a ∨ (a ∧ b) = a, a ∧ (a ∨ b) = a</Text>
        <Text style={styles.lawRow}><Text style={styles.bold}>Commutative:</Text> a ∨ b = b ∨ a, a ∧ b = b ∧ a</Text>
      </View>

      <Text style={styles.sectionHeader}>Conclusion</Text>
      <Text style={styles.paragraph}>
        In this chapter, we explained the progression from semigroups to groups, explored subgroups and cyclic groups, and analyzed the logical ordering within POSETs and Lattices. These structures provide a foundational framework for discrete mathematics and computational logic.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF', padding: 15 },
  sectionHeader: { fontSize: 19, fontWeight: '900', color: '#0F172A', marginTop: 25, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: '#16941c', paddingLeft: 10 },
  subHeader: { fontSize: 16, fontWeight: '700', color: '#334155', marginTop: 15, marginBottom: 5 },
  paragraph: { fontSize: 15, color: '#475569', lineHeight: 24, marginBottom: 12, textAlign: 'justify' },
  bold: { fontWeight: 'bold', color: '#1E293B' },
  nodeContainer: { marginBottom: 15, alignItems: 'center' },
  nodeBox: { width: '90%', padding: 15, backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center' },
  nodeName: { fontSize: 16, fontWeight: 'bold', color: '#16941c' },
  nodeDesc: { fontSize: 12, color: '#64748B', textAlign: 'center', marginTop: 4 },
  propertyPills: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 5, marginTop: 8 },
  pill: { backgroundColor: '#F0FDF4', paddingVertical: 4, paddingHorizontal: 8, borderRadius: 20, borderWidth: 1, borderColor: '#BBF7D0' },
  pillText: { fontSize: 10, color: '#166534', fontWeight: 'bold' },
  exampleBox: { paddingLeft: 15, marginBottom: 20, borderLeftWidth: 1, borderLeftColor: '#E2E8F0' },
  exampleText: { fontSize: 13, color: '#64748B', fontStyle: 'italic' },
  infoBox: { backgroundColor: '#F0F9FF', padding: 15, borderRadius: 12, borderLeftWidth: 4, borderLeftColor: '#0369A1', marginBottom: 20 },
  diagramContainer: { alignItems: 'center', marginVertical: 20, padding: 15, backgroundColor: '#FAFAFA', borderRadius: 15 },
  caption: { fontSize: 11, color: '#94A3B8', marginTop: 10, textAlign: 'center' },
  propertyCard: { backgroundColor: '#FDF2F8', padding: 15, borderRadius: 12, marginBottom: 15 },
  propertyTitle: { fontSize: 15, fontWeight: 'bold', color: '#BE185D', marginBottom: 10 },
  propertyText: { fontSize: 13, color: '#9D174D', marginBottom: 6 },
  lawCard: { backgroundColor: '#FFF7ED', padding: 15, borderRadius: 12, marginBottom: 15 },
  lawRow: { fontSize: 13, color: '#9A3412', marginBottom: 5, fontFamily: 'monospace' },
  divider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 15 }
});