import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';

export default function ArithmeticGeometric_6_2() {
  
  // Custom Component for Sequence Formula Comparison
  const FormulaComparison = ({ title, recursive, closed, color }) => (
    <View style={[styles.formulaCard, { borderTopColor: color }]}>
      <Text style={[styles.formulaTitle, { color: color }]}>{title}</Text>
      <View style={styles.formulaRow}>
        <View style={styles.formulaHalf}>
          <Text style={styles.label}>Recursive</Text>
          <Text style={styles.mathText}>{recursive}</Text>
        </View>
        <View style={styles.verticalDivider} />
        <View style={styles.formulaHalf}>
          <Text style={styles.label}>Closed</Text>
          <Text style={styles.mathText}>{closed}</Text>
        </View>
      </View>
    </View>
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={{paddingBottom: 100}} showsVerticalScrollIndicator={false}>
      
      <Text style={styles.paragraph}>
        {"In Discrete Mathematics, we use sequences to understand patterns and predict subsequent terms. Arithmetic and geometric sequences form the basics for understanding numbers that increase either additively or multiplicatively."}
      </Text>

      {/* SECTION 1: ARITHMETIC SEQUENCES */}
      <Text style={styles.sectionHeader}>{"Arithmetic Sequences"}</Text>
      <Text style={styles.paragraph}>
        {"A sequence where each term is generated by adding a constant known as the "}<Text style={styles.bold}>{"common difference (d)"}</Text>{" to the previous term."}
      </Text>

      <FormulaComparison 
        title={"Arithmetic Logic (d = common difference)"}
        recursive={"an = an-1 + d"}
        closed={"an = a0 + n \u00b7 d"}
        color={"#16941c"}
      />

      <View style={styles.exampleBox}>
        <Text style={styles.bold}>{"Example: 3, 7, 11, 15..."}</Text>
        <Text style={styles.exampleText}>{"Initial (a0) = 3 | Difference (d) = 4"}</Text>
        <Text style={styles.resultText}>{"a4 (5th term) = 3 + 4 \u00d7 4 = 19"}</Text>
      </View>

      {/* SECTION 2: GEOMETRIC SEQUENCES */}
      <Text style={styles.sectionHeader}>{"Geometric Sequences"}</Text>
      <Text style={styles.paragraph}>
        {"These differ in that each term is generated by multiplying the previous term by a constant known as the "}<Text style={styles.bold}>{"common ratio (r)"}</Text>{"."}
      </Text>

      <FormulaComparison 
        title={"Geometric Logic (r = common ratio)"}
        recursive={"an = an-1 \u00b7 r"}
        closed={"an = a0 \u00b7 r^n"}
        color={"#0369A1"}
      />

      <View style={styles.exampleBox}>
        <Text style={styles.bold}>{"Example: 2, 6, 18, 54..."}</Text>
        <Text style={styles.exampleText}>{"Initial (a0) = 2 | Ratio (r) = 3"}</Text>
        <Text style={styles.resultText}>{"a3 (4th term) = 2 \u00b7 3^3 = 54"}</Text>
      </View>

      {/* SECTION 3: REAL WORLD APPLICATIONS */}
      <Text style={styles.sectionHeader}>{"Real-World Applications"}</Text>
      
      <View style={styles.appCard}>
        <View style={styles.appHeader}>
          <MaterialCommunityIcons name="cash-plus" size={24} color="#16941c" />
          <Text style={styles.appTitle}>{"Salary Growth (Arithmetic)"}</Text>
        </View>
        <Text style={styles.appText}>
          {"A salary starting at Rs. 500,000 with a yearly increase of Rs. 50,000 follows an arithmetic progression."}
        </Text>
        <Text style={styles.mathBadge}>{"a5 = 500,000 + 50,000 \u00b7 5 = 750,000"}</Text>
      </View>

      <View style={styles.appCard}>
        <View style={styles.appHeader}>
          <MaterialCommunityIcons name="account-group-outline" size={24} color="#0369A1" />
          <Text style={styles.appTitle}>{"Population Growth (Geometric)"}</Text>
        </View>
        <Text style={styles.appText}>
          {"A town of 1,000 people growing by 5% each year forms a geometric sequence where r = 1.05."}
        </Text>
        <Text style={styles.mathBadge}>{"a10 = 1000 \u00b7 (1.05)^10 \u2248 1,629 people"}</Text>
      </View>

      <View style={styles.appCard}>
        <View style={styles.appHeader}>
          <MaterialCommunityIcons name="bank-outline" size={24} color="#7C3AED" />
          <Text style={styles.appTitle}>{"Compound Interest (Geometric)"}</Text>
        </View>
        <Text style={styles.appText}>
          {"Investing Rs. 5,000 at 4% interest compounded annually follows a geometric sequence with r = 1.04."}
        </Text>
        <Text style={styles.mathBadge}>{"a6 = 5000 \u00b7 (1.04)^6 \u2248 6,326"}</Text>
      </View>

      <Text style={styles.sectionHeader}>{"Conclusion"}</Text>
      <Text style={styles.paragraph}>
        {"In this chapter, we explained arithmetic sequences involving constant differences and geometric sequences relying on common ratios. We understood both recursive and closed formulas for each type and explored diverse applications from financial modelling to town population predictions."}
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF', padding: 15 },
  sectionHeader: { fontSize: 19, fontWeight: '900', color: '#0F172A', marginTop: 25, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: '#16941c', paddingLeft: 10 },
  paragraph: { fontSize: 15, color: '#475569', lineHeight: 24, marginBottom: 12, textAlign: 'justify' },
  bold: { fontWeight: 'bold', color: '#1E293B' },
  formulaCard: { backgroundColor: '#F8FAFC', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', borderTopWidth: 5, marginBottom: 15 },
  formulaTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 12, textTransform: 'uppercase' },
  formulaRow: { flexDirection: 'row', alignItems: 'center' },
  formulaHalf: { flex: 1, alignItems: 'center' },
  label: { fontSize: 10, color: '#64748B', marginBottom: 4, fontWeight: 'bold' },
  mathText: { fontFamily: 'monospace', fontSize: 14, fontWeight: 'bold', color: '#0F172A' },
  verticalDivider: { width: 1, height: '80%', backgroundColor: '#E2E8F0', marginHorizontal: 10 },
  exampleBox: { backgroundColor: '#F0FDF4', padding: 15, borderRadius: 10, marginBottom: 20 },
  exampleText: { fontSize: 13, color: '#166534', marginTop: 4 },
  resultText: { fontSize: 14, color: '#166534', fontWeight: 'bold', textAlign: 'right', marginTop: 8 },
  appCard: { backgroundColor: '#FFF', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 15 },
  appHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  appTitle: { fontSize: 15, fontWeight: 'bold', color: '#1E293B', marginLeft: 10 },
  appText: { fontSize: 13, color: '#475569', lineHeight: 20 },
  mathBadge: { backgroundColor: '#F1F5F9', padding: 8, borderRadius: 6, marginTop: 12, textAlign: 'center', fontFamily: 'monospace', fontSize: 12, color: '#0F172A', fontWeight: 'bold', overflow: 'hidden' }
});